config/routes.rb
Downhill::Application.routes.draw do

  # require 'sidekiq/web'
  # mount Sidekiq::Web => '/sidekiq'

  match '/users/auth/email/callback' => 'omniauth_callbacks#authorize_campaign_monitor', via: [:get, :post]
  match '/users/auth/:action/callback' => 'omniauth_callbacks#authorize_stripe', via: [:get, :post]

  get '/validate_referral_code/:code/:event_id' => "orders#validate_referral_code", :path => "/validate_referral_code/:code/:event_id"
  get '/validate_email_uniqueness/' => "orders#validate_email_uniqueness", :path => "/validate_email_uniqueness/"

  post '/orders/:event_id' => "orders#create", :as => "/"

  devise_for :users
  devise_for :participants, :controllers => { :registrations => "participants" }


  resources :settings
  resources :users
  resources :participants
  resources :teams
  resources :customers
  resources :campaign_monitors


  get '/:event_id/fee' => "fee#index", :as => "fees"
  post '/fee/:event_id' => "fee#create", :as => "/"
  get '/fee/new' => "fee#new", :as => "new_fee"
  get '/edit/:id/fee' => "fee#edit", :as => "edit_fee"
  get '/fee/:id' => "fee#show", :as => "fee"
  put '/fee/:id' => "fee#update"
  patch '/fee/:id' => "fee#update"
  delete '/fee/:id' => "fee#destroy"

  get '/:event_id/ticket' => "ticket#index", :as => "tickets"
  post '/ticket/:event_id' => "ticket#create", :as => "/"
  get '/ticket/new' => "ticket#new", :as => "new_ticket"
  get '/edit/:id/ticket' => "ticket#edit", :as => "edit_ticket"
  get '/ticket/:id' => "ticket#show", :as => "ticket"
  put '/ticket/:id' => "ticket#update"
  patch '/ticket/:id' => "ticket#update"
  delete '/ticket/:id' => "ticket#destroy"

  get '/:event_id/waves' => "waves#index", :as => "waves"
  post '/waves/:event_id' => "waves#create", :as => "/"
  get '/waves/new' => "waves#new", :as => "new_wave"
  get '/edit/:id/waves' => "waves#edit", :as => "edit_wave"
  get '/waves/:id' => "waves#show", :as => "wave"
  put '/waves/:id' => "waves#update"
  patch '/waves/:id' => "waves#update"
  delete '/waves/:id' => "waves#destroy"

  get '/:event_id/promo_codes' => "promo_codes#index", :as => "promo_codes"
  post '/promo_codes/:event_id' => "promo_codes#create", :as => "/"
  get '/promo_codes/new' => "promo_codes#new", :as => "new_promo_code"
  get '/edit/:id/promo_codes' => "promo_codes#edit", :as => "edit_promo_code"
  get '/promo_codes/:id' => "promo_codes#show", :as => "promo_code"
  put '/promo_codes/:id' => "promo_codes#update"
  patch '/promo_codes/:id' => "promo_codes#update"
  delete '/promo_codes/:id' => "promo_codes#destroy"

  get '/:event_id/affiliate_settings' => "affiliate_settings#index", :as => "affiliate_settings"
  post '/affiliate_settings/:event_id' => "affiliate_settings#create", :as => "/"
  get '/affiliate_settings/new' => "affiliate_settings#new", :as => "new_affiliate_settings"
  get '/edit/:id/affiliate_settings' => "affiliate_settings#edit", :as => "edit_affiliate_settings"
  get '/affiliate_settings/:id' => "affiliate_settings#show", :as => "affiliate_setting"
  put '/affiliate_settings/:id' => "affiliate_settings#update"
  patch '/affiliate_settings/:id' => "affiliate_settings#update"
  delete '/affiliate_settings/:id' => "affiliate_settings#destroy"

  get '/:event_id/orders/new' => "orders#new", :as => "new_order"
  post '/orders/:event_id' => "orders#create", :as => "/"
  get '/:event_id/success' => "orders#success", :as => "success_order"

  get '/dashboard' => 'dashboards#show'

  get '/events/:id/registration' => "events#edit", :as => "registration"
  get '/events/:id/publish' => "events#edit", :as => "publish"
  get '/events/:id/other_info' => "events#edit", :as => "other_info"
  get '/events/:id/waiver' => "events#waiver", :as => "event_waiver"

  resources :events

  get '/events/:id/(/:referral_code)' => 'events#show', :as => "public_event"

  # get '/faq' => "pages#faq"
  root 'pages#home'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_authorization_check
  layout "home"

  def index
    cookies[:_cookietest_session] = {domain: COOKIE_DOMAIN}
  end
  
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<!DOCTYPE html>
<html lang="en">

  <body class="page">

    <header role="banner" class="transparent light">
      <div class="row">
        <div class="nav-inner row-content buffer-left buffer-right even clear-after">
          <div id="brand">
            <h1 class="reset"><a href="<%= root_url %>">Ticket Science</a></h1>
          </div><!-- brand -->
          <a id="menu-toggle" href="#"><i class="fa fa-bars fa-lg"></i></a>
          <nav>
            <ul class="reset" role="navigation">
              <% if user_signed_in? %>
                <li class="menu-item">
                  <a href="<%= dashboard_url %>">Dashboard</a>
                </li>
              <% else %>
                <li class="menu-item">
                  <a href="<%= new_user_registration_url %>">Create an Event</a>
                </li>
                <li class="menu-item">
                  <a href="<%= new_user_session_url %>">Login</a>
                </li>
              <% end %>
            </ul>
          </nav>
        </div><!-- row-content -->  
      </div><!-- row -->  
    </header>

    <main role="main">
      <div id="intro-wrap">
        <div id="intro" class="darken" data-autoplay="5000" data-navigation="true" data-pagination="true" data-transition="fadeUp">         

          <div class="intro-item" style="background-image: url(<%= image_url 'desktop.jpg' %>);">  
            <div class="caption" style="top: 200px;">
              <h2>The Best Way to Organize Themed Races</h2>
              <p>Ticketing, Waves, Affiliate marketing all built in</p>
              <a class="button white transparent" href="<%= new_user_registration_url %>">Create your event for free</a>
            </div><!-- caption -->           
          </div> 

        </div><!-- intro -->
      </div><!-- intro-wrap -->

      <div id="main">
         <section class="row section text-light greyish" style="background-color: #FC6E51">
          <div class="row-content buffer even clear-after">
            <div class="column four centertxt">
              <div class="big-icon red"><i class="icon icon-graph"></i></div>
                <div class="big-icon-text clear-after">
                  <h4>Affiliate Marketing</h4>
                    <p class="text-s">Incentivize your customers to market for you. When they get their friends to purchase event tickets, they get a small cut (amount determined by you if you turn affiliates on).</p>
                </div>
            </div>
            <div class="column four centertxt">
              <div class="big-icon red"><i class="icon icon-clock"></i></div>
                <div class="big-icon-text clear-after">
                  <h4>Ticket and Wave Times</h4>
                  <p class="text-s">Want multiple waves for every ticket? Volunteer tickets? We have all that, built in from the ground up.</p>
                </div>
            </div>            
            <div class="column four last centertxt">
              <div class="big-icon red"><i class="icon icon-money"></i></div>
                <div class="big-icon-text clear-after">
                  <h4>Get Paid Fast</h4>
                  <p class="text-s">Unlike Active, we don't hold your money hostage. Get paid on every ticket on a two day rolling basis.</p>
                </div>
            </div>
          </div>
        </section>  



        <section class="row section text-light greyish" style="background-color:#4FC1E9;">
          <div class="row-content buffer even clear-after" style="padding-top:30px;">         
            <div class="section-title" style="padding-bottom:30px"><h2>Increase Your Revenue per Customer</h2></div>
            <div class="blog-section masonry-style preload">
               <article class="test clearfix">
                      <%= image_tag "img3.png", :class => "left" %>
                      <div class="right">
                        <h3 class="column">Mobile Checkout</h3>
                        <ul>
                          <li>Event pages optimized for smartphones</li>
                          <li>Easy mobile checkout</li>
                          <li>Upsells </li>
                        </ul>
                      </div>
              </article>                    
           
              <article class="test clearfix">
                      <%= image_tag "img3.png", :class => "right" %>
                      <div class="left">
                        <h3 class="column">Sell More Merchandise</h3>
                        <ul>
                          <li>Add upsells to checkout</li>
                          <li>Analyze what sells best</li>
                          <li>Included automatically for all events</li>
                        </ul>
                      </div>
              </article> 

              <article class="test clearfix">
                      <%= image_tag "img3.png", :class => "left" %>
                      <div class="right">
                        <h3 class="column">Flexible Reporting</h3>
                        <ul>
                          <li>Custom date ranges</li>
                          <li>Issue refunds yourself</li>
                          <li>Filter by Event</li>
                        </ul>
                      </div>
              </article>
                                   
              <div class="shuffle-sizer three"></div>
            </div><!-- grid-items -->
          </div>  
        </section>  

        <section class="row section text-light test" style="background-color:#f2955f">
              
          <h2 class="orange">We Charge Only When You Do</h2>
          <h4 class="orange">$2.95 per ticket if paid. Free tickets are free!</h2>

          <div class="more-btn"><a class="button transparent white" href="<%= new_user_registration_path %>">Create Your Event For Free</a></div>                      
        </section>                        

        <section class="row section call-to-action">
          <div class="row-content buffer even">
            <p>What are you waiting for?</p>
            <a class="button red" href="<%= new_user_registration_path %>">Create an event for free</a>
          </div>
        </section>             

      </div><!-- id-main -->
    </main><!-- main -->

    <footer role="contentinfo">
      <div class="row">
        <div class="row-content buffer clear-after">
          <section id="top-footer">
            <div class="widget column three"><!-- la class="widget" è forse generata utomaticamente da wp -->
              <h4>Menu</h4>
              <ul class="plain">
                <li><a href="<%= root_url %>">Home</a></li>
                <li><a href="#">FAQ</a></li>
                <li><a href="#">Contact</a></li>
              </ul>
            </div>
                    
            <div class="widget meta-social column three">
              <h4>Follow Us</h4>
              <ul class="inline">
                <li><a href="#" class="twitter-share border-box"><i class="fa fa-twitter fa-lg"></i></a></li>
                <li><a href="#" class="facebook-share border-box"><i class="fa fa-facebook fa-lg"></i></a></li>
                <li><a href="#" class="pinterest-share border-box"><i class="fa fa-pinterest fa-lg"></i></a></li>
              </ul>
            </div>                            
          </section><!-- top-footer -->
          <section id="bottom-footer">
            <p class="keep-left">&copy; 2014 Ticket Science</p>
          </section><!-- bottom-footer -->      
        </div><!-- row-content -->  
      </div><!-- row -->  
    </footer>
<%= javascript_include_tag "https://code.jquery.com/jquery.js" %>
<%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?sensor=false" %>
<%= javascript_include_tag "beetle/plugins.js" %>
<%= javascript_include_tag "beetle/beetle.js" %>

  </body>

</html>