config/routes.rb
Downhill::Application.routes.draw do

  # require 'sidekiq/web'
  # mount Sidekiq::Web => '/sidekiq'

  match '/users/auth/email/callback' => 'omniauth_callbacks#authorize_campaign_monitor', via: [:get, :post]
  match '/users/auth/:action/callback' => 'omniauth_callbacks#authorize_stripe', via: [:get, :post]

  get '/validate_referral_code/:code/:event_id' => "orders#validate_referral_code", :path => "/validate_referral_code/:code/:event_id"
  get '/validate_email_uniqueness/' => "orders#validate_email_uniqueness", :path => "/validate_email_uniqueness/"

  post '/orders/:event_id' => "orders#create", :as => "/"

  devise_for :users
  devise_for :participants, :controllers => { :registrations => "participants" }


  resources :settings
  resources :users
  resources :participants
  resources :teams
  resources :customers
  resources :campaign_monitors


  get '/:event_id/fee' => "fee#index", :as => "fees"
  post '/fee/:event_id' => "fee#create", :as => "/"
  get '/fee/new' => "fee#new", :as => "new_fee"
  get '/edit/:id/fee' => "fee#edit", :as => "edit_fee"
  get '/fee/:id' => "fee#show", :as => "fee"
  put '/fee/:id' => "fee#update"
  patch '/fee/:id' => "fee#update"
  delete '/fee/:id' => "fee#destroy"

  get '/:event_id/ticket' => "ticket#index", :as => "tickets"
  post '/ticket/:event_id' => "ticket#create", :as => "/"
  get '/ticket/new' => "ticket#new", :as => "new_ticket"
  get '/edit/:id/ticket' => "ticket#edit", :as => "edit_ticket"
  get '/ticket/:id' => "ticket#show", :as => "ticket"
  put '/ticket/:id' => "ticket#update"
  patch '/ticket/:id' => "ticket#update"
  delete '/ticket/:id' => "ticket#destroy"

  get '/:event_id/waves' => "waves#index", :as => "waves"
  post '/waves/:event_id' => "waves#create", :as => "/"
  get '/waves/new' => "waves#new", :as => "new_wave"
  get '/edit/:id/waves' => "waves#edit", :as => "edit_wave"
  get '/waves/:id' => "waves#show", :as => "wave"
  put '/waves/:id' => "waves#update"
  patch '/waves/:id' => "waves#update"
  delete '/waves/:id' => "waves#destroy"

  get '/:event_id/promo_codes' => "promo_codes#index", :as => "promo_codes"
  post '/promo_codes/:event_id' => "promo_codes#create", :as => "/"
  get '/promo_codes/new' => "promo_codes#new", :as => "new_promo_code"
  get '/edit/:id/promo_codes' => "promo_codes#edit", :as => "edit_promo_code"
  get '/promo_codes/:id' => "promo_codes#show", :as => "promo_code"
  put '/promo_codes/:id' => "promo_codes#update"
  patch '/promo_codes/:id' => "promo_codes#update"
  delete '/promo_codes/:id' => "promo_codes#destroy"

  get '/:event_id/affiliate_settings' => "affiliate_settings#index", :as => "affiliate_settings"
  post '/affiliate_settings/:event_id' => "affiliate_settings#create", :as => "/"
  get '/affiliate_settings/new' => "affiliate_settings#new", :as => "new_affiliate_settings"
  get '/edit/:id/affiliate_settings' => "affiliate_settings#edit", :as => "edit_affiliate_settings"
  get '/affiliate_settings/:id' => "affiliate_settings#show", :as => "affiliate_setting"
  put '/affiliate_settings/:id' => "affiliate_settings#update"
  patch '/affiliate_settings/:id' => "affiliate_settings#update"
  delete '/affiliate_settings/:id' => "affiliate_settings#destroy"

  get '/:event_id/orders/new' => "orders#new", :as => "new_order"
  post '/orders/:event_id' => "orders#create", :as => "/"
  get '/:event_id/success' => "orders#success", :as => "success_order"

  get '/dashboard' => 'dashboards#show'

  get '/events/:id/registration' => "events#edit", :as => "registration"
  get '/events/:id/publish' => "events#edit", :as => "publish"
  get '/events/:id/other_info' => "events#edit", :as => "other_info"
  get '/events/:id/waiver' => "events#waiver", :as => "event_waiver"

  resources :events

  get '/events/:id/(/:referral_code)' => 'events#show', :as => "public_event"

  # get '/faq' => "pages#faq"
  root 'pages#home'

end

app/models/event.rb
class Event < ActiveRecord::Base
  validates :title, :presence => true
  validates :date, :presence => true
  validates :time, :presence => true

  has_paper_trail
  
  before_create :defaults

  belongs_to :account
  has_many :user_events
  has_many :users, :through => :user_events

  has_many :tickets
  has_many :fees
  has_many :waves
  has_many :teams
  has_many :orders
  has_many :promo_codes
  has_many :affiliate_codes

  has_one :affiliate_setting

  def date=(string)
    if string.present?
      val = Date.strptime(string, '%m/%d/%Y')
      write_attribute :date, val
    end
  end

  def defaults
    self.affiliate_setting = AffiliateSetting.create
    self.path = self.title.parameterize
  end

  def user
    self.users.find_by type: "User"
  end

  def add_participant(participant, team, wave, signature, ticket)
    participant.teams << team if team
    wave.users << participant
    ticket.users << participant
    self.users << participant
    participant.assign_affiliate_code(self).save
    self.add_waiver_signature(signature, participant)
  end

   def add_waiver_signature(signature, participant)
    unless signature == ""
      user_event = self.user_events.find_by user_id: participant
      user_event.waiver_signature = signature
      user_event.save
    end
  end

  def fee_total
    self.fees.map(&:amount).inject(0, &:+)
  end

  def sales(start_day = nil, end_day = 1)
    if start_day.class == Fixnum && end_day.class == Fixnum
      orders = self.orders.where(created_at: (Time.now.midnight - start_day.day)..(Time.now.midnight - end_day.day + 86400) )
      sales = orders.collect { |order| order.amount }
    else
      sales = self.orders.collect { |order| order.amount }
    end
    sales.compact.sum
  end

  def code_is_valid?(string)
    self.valid_codes.any? { |code| code.code == string }
  end

  def valid_codes
    promo_codes = self.promo_codes.to_a
    affiliate_codes = self.affiliate_codes.to_a
    promo_codes + affiliate_codes
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  layout "event", only: [:show, :waiver]
  authorize_resource
  
  before_action :check_subdomain, :except => [:show]
  before_action :authenticate_user!, except: [:show]
  before_action :set_event, only: [:edit, :update, :destroy, :show, :waiver]  
  
  # skip_before_action :check_subdomain, :only => [:show]

  # GET /events
  # GET /events.json

  def waiver
  end

  def index
    @events = current_user.events
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @participant = Participant.new
    session[:referral_code] = params[:referral_code]
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = current_user.account.events.build(event_params)

    respond_to do |format|
      if @event.save
        @event.users << current_user
        format.js { render :js => "window.location.href = '#{edit_event_url(@event)}'" }
      else
        format.js
        format.html { render 'new' }
      end
    end

  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    @event.user.account.update(account_params)
    
    if @event.update(event_params)
      redirect_to :back
    else
      redirect_to dashboard_path
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to profile_url }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.

    def set_event
      @user = find_user
      @event = @user.events.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(
        :title, 
        :waiver, 
        :description, 
        :time, 
        :path, 
        :id, 
        :street_address_one, 
        :street_address_two, 
        :city, 
        :state, 
        :zipcode, 
        :date,
        :timezone, 
        :volunteer_coordinator_email, 
        :support_email, 
        :google_maps_iframe, 
        :receipt_html,
        :packet_pickup_info_html,
        :race_day_info_html,
        :published,
        :on_sale,
        :about,
        :packet_info,
        :deadline_pricing_info,
        :volunteer_info,
        :charity_info
        )
    end

    def ticket_params
      params.require(:event).permit(ticket: [{:ticket_type => [], :price => [], :for_sale_begin => [], :for_sale_end => [] }])
    end

    def account_params
      params.require(:event).permit(account:[:header,:footer])
    end

    def wave_params
      params.require(:event).permit(wave: [{:start_time => [], :title => [], :quantity => [] }])
    end

    def fee_params
      params.require(:event).permit(fee: [{:name => [], :amount => [] }])
    end


end

app/helpers/events_helper.rb
module EventsHelper

  def wave_collection(waves)
    waves.collect do |wave|
    end
  end

  def card_expiration_year
    if Rails.env.development?
      2020
    else
      Date.today.year
    end
  end

  def page_not_found
    raise ActionController::RoutingError.new('Not Found')
  end

  def wave_titles
    array = Array.new
    @event.waves.each do |wave|
      array.push(["#{wave.title}" + " - " + "#{format_time(wave.start_time)}" + " - " "#{waves_remaining(wave)} remaining!",wave.id])
    end
    array
  end

  def waves_remaining(wave)
    wave.quantity - wave.users.count
  end

  def ticket_titles
    array = Array.new
    @event.tickets.each do |ticket|
      array.push(["#{ticket.ticket_type}",ticket.id])
    end
    array
  end

  def tickets_remaining(ticket)
    ticket.quantity - ticket.users.count
  end

end

app/views/events/_contact_info.html.erb
<div class="form-group">
  <%= f.label :support_email, "Support contact email address" %>
  <%= f.text_field :support_email, :placeholder => "sally@amazingrace.com", :class => "form-control" %>
</div>

<div class="form-group">
  <%= f.label :volunteer_coordinator_email %>
  <%= f.text_field :volunteer_coordinator_email, :placeholder => "volunteer_lead@amazingrace.com", :class => "form-control" %>
</div>

app/views/events/_errors.html.erb
<% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

app/views/events/_event_details.html.erb
<%= render 'new_event_details', :f => f %>

<div class="form-group">
  <%= f.label :street_address_one, "Street Address" %>
  <%= f.text_field :street_address_one, :placeholder => "123 Parkway", :class => "form-control" %>
</div>

<div class="form-group">
  <%= f.label :street_address_two, "Street Address" %>
  <%= f.text_field :street_address_two, :class => "form-control" %>
</div>

<div class="form-group">
  <%= f.label :city %>
  <%= f.text_field :city, :placeholder => "Mountain View", :class => "form-control" %>
</div>

<div class="form-group">
  <%= f.label :state %>
  <%= f.text_field :state, :placeholder => "CA", :class => "form-control" %>
</div>

<div class="form-group">
  <%= f.label :zipcode %>
  <%= f.text_field :zipcode, :placeholder => "94806", :class => "form-control" %>
</div>

<div class="form-group">
  <%= f.label :google_maps_iframe, "Google Maps Embed Link" %>
  <%= f.text_field :google_maps_iframe, :class => "form-control" %>
</div>

<%= f.submit :class => "btn btn-primary" %>

app/views/events/_event_footer.html.erb
<div id="footer" class="margin-top">
      <div class="wrapper clearfix">
        <div class="copy left">
        </div><!-- /.copy -->
        <div class="powered right">
          <span class="left">Powered By</span>
          <%= link_to (image_tag "psd_html/ticket-science-logo.png"), "http://#{DOMAIN_NAME}" %>
        </div><!-- /.powered right -->
      </div><!-- /.wrapper -->
    </div><!-- /#footer -->

app/views/events/_form.html.erb
<%= render "layouts/left_panel" %>
<div id="main" role="main">
<div id="content">

<%= form_for(@event) do |f| %>

  <%= render 'errors', :f => f %>
  <%= render 'event_details', :f => f if last_path(request.path) == "edit" %>
  <%= render 'registration', :f => f if last_path(request.path) == "registration" %>
  <%= render 'publish', :f => f if last_path(request.path) == "publish" %>

<% end %>
</div>
</div>
<%= javascript_include_tag "smart-admin/app" %>

app/views/events/_hidden_modules.html.erb
<div class="hide" id="new_fee_form">
  <%= render "fee/form", :f => f %> 
</div>
<div class="hide" id="new_wave_form">
  <%= render "waves/form", :f => f %> 
</div>

app/views/events/_plane_description.html.erb
<div class="row">
  <div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
    <h1 class="page-title txt-color-blueDark">
      <i class="fa-fw fa fa-calendar"></i>
      <% if @event.title %>
        <%= @event.title %>
      <% else %>
        <%= "New Event" %>
      <% end %>
    </h1>

  </div>

  <div class="actions">
    <% if @event.title %>
      <%= f.submit "Save Changes", :class => "btn btn-primary pull-right save" %>
    <% else %>
      <%= f.submit "Create Event", :class => "btn btn-primary pull-right save" %>
    <% end %>
  </div>
</div>

app/views/events/_registration.html.erb
<div class="form-group">
  <%= fields_for @event.user.account do |builder| %>
    <%= builder.label :header, "Custom header HTML/CSS" %>
    <%= builder.text_area :header, :class => "form-control" %>
  <% end %>
</div>

<div class="form-group">
  <%= fields_for @event.user.account do |builder| %>
    <%= builder.label :footer, "Custom footer HTML/CSS" %>
    <%= builder.text_area :footer, :class => "form-control" %>
  <% end %>
</div>

<div class="form-group">
  <%= f.label :about, "Event Description (tab1)" %>
  <%= f.text_area :about, :cols => "50", :rows => "5", :placeholder => "About the Event", :class => "form-control" %>
</div>

<div class="form-group">
  <%= f.label :packet_info, "What Comes in the Packet? (tab2)" %>
  <%= f.text_area :packet_info, :class => "form-control editor", :rows => "5" %>
</div>

<div class="form-group">
  <%= f.label :packet_pickup_info_html, "Packet Pickup Info (tab3)" %>
  <%= f.text_area :packet_pickup_info_html, :class => "form-control editor", :rows => "5" %>
</div>

<div class="form-group">
  <%= f.label :race_day_info_html, "Race Day Info (tab4)" %>
  <%= f.text_area :race_day_info_html, :class => "form-control editor", :rows => "5" %>
</div>

<div class="form-group">
  <%= f.label :deadline_pricing_info, "Deadline and Pricing Info (tab5)" %>
  <%= f.text_area :deadline_pricing_info, :class => "form-control editor", :rows => "5" %>
</div>

<div class="form-group">
  <%= f.label :volunteer_info, "Volunteer Info (tab6)" %>
  <%= f.text_area :volunteer_info, :class => "form-control editor", :rows => "5" %>
</div>

<div class="form-group">
  <%= f.label :charity_info, "Charity Info (tab7)" %>
  <%= f.text_area :charity_info, :class => "form-control editor", :rows => "5" %>
</div>

<div class="form-group">
  <%= f.label :waiver, "Waiver text" %>
  <%= f.text_area :waiver, :cols => "50", :rows => "3", :placeholder => "Text so you don't get sued", :class => "form-control" %>
</div>

<div class="form-group">
  <%= f.label :receipt_html, "Receipt sent after signups" %>
  <%= f.text_area :receipt_html, :class => "form-control editor", :rows => "5" %>
</div>

<%= f.submit :class => "btn btn-primary" %>

app/views/events/_stripe_publishable_key.html.erb
<script type="text/javascript">
  Stripe.setPublishableKey('<%= @user.stripe_publishable_key %>');
</script>

app/views/events/create.js.erb
<% if @event.errors.count > 0 %>
    $('#event_error_explanation').html("");
  <% @event.errors.full_messages.each do |message| %>
    $('#event_error_explanation').append("<%= message %>");
    $('#event_error_explanation').append("<br>");    
  <% end %>
  document.getElementById("event_error_explanation").style.display = 'block';
<% else %>
  document.getElementById("event_error_explanation").style.display = 'none';
<% end %>

app/views/events/index.html.erb
<div id="content">
<section id="widget-grid" class="">
        
          <!-- row -->
          <div class="row">
        
            <!-- NEW WIDGET START -->
            <article class="col-xs-12 col-sm-12 col-md-12 col-lg-12 sortable-grid ui-sortable">
        
            <div class="jarviswidget jarviswidget-sortable jarviswidget-color-blueLight" id="wid-id-0" data-widget-fullscreenbutton="false" data-widget-togglebutton="false" data-widget-deletebutton="false" data-widget-colorbutton="false"  data-widget-editbutton="false" role="widget" style="" data-widget-attstyle="jarviswidget-color-green">

              <header role="heading">
                  <span class="widget-icon"> <i class="fa fa-table"></i> </span>
                  <h2>All Events</h2>
              </header>
        
                <!-- widget div-->
                <div role="content">
  
                  <!-- widget content -->
                  <div class="widget-body no-padding">

                  <% if @events.blank? %>
                    <br>
                    <h1 style="font-size:30px; margin-left: 10px;">You haven't created any events yet.</h1>
                    <h4 style="font-size:15px; margin-left: 10px;">Make your first by clicking the "Create an Event" button below!</h4>
                    <br>
                  <% else %>

                     
                    <div class="dt-wrapper">
                      <table id="dt_basic" class="table table-striped table-bordered table-hover dataTable" aria-describedby="dt_basic_info">
                      <thead>
                        <tr role="row">
                          <th class="sorting" role="columnheader" tabindex="0" aria-controls="dt_basic" rowspan="1" colspan="1" aria-label="Name: activate to sort column ascending" style="width: 150px;">Event</th>
                          <th class="sorting" role="columnheader" tabindex="0" aria-controls="dt_basic" rowspan="1" colspan="1" aria-label="Name: activate to sort column ascending" style="width: 150px;">Event Preview link</th>
                          <th class="sorting" role="columnheader" tabindex="0" aria-controls="dt_basic" rowspan="1" colspan="1" aria-label="Phone: activate to sort column ascending" style="width: 126px;">Date</th>
                          <th class="sorting" role="columnheader" tabindex="0" aria-controls="dt_basic" rowspan="1" colspan="1" aria-label="Company: activate to sort column ascending" style="width: 110px;">Tickets Sold</th>
                          <th class="sorting" role="columnheader" tabindex="0" aria-controls="dt_basic" rowspan="1" colspan="1" aria-label="Zip: activate to sort column ascending" style="width: 83px;">Live?</th>
                        </tr>
                      </thead>
                      <tbody role="alert" aria-live="polite" aria-relevant="all">
                      <% @events.each do |event| %> 
                          <tr class="<%= cycle("odd", "even") -%>">
                            <td class=" "><%= link_to event.title, edit_event_path(event) %></td>
                            <td class=" "><%= link_to "Preview Event Page", event_path(event), :target => '_blank' %></td>
                            <td class=" "><%= event.date.strftime("%B %d, %Y") unless event.date.nil? %></td>
                            <td class=" "><%= event.users.where(:type => "Participant").count %></td>
                            <td class=" "><% if event.published %>
                                          <%= "Yes" %>
                                          <% else %> 
                                          <%= "No" %>
                                          <% end %> </td>
                          </tr>
                      <% end %>
                      </tbody>
                    </table>
                  </div>
                
              
                  <% end %>

                    </div></div>

                    <%= button_to "Create an Event", new_event_url, :method => "get", :class => "btn btn-success btn-lg pull-left header-btn hidden-mobile" %>
        
                  </div>
                  <!-- end widget content -->
        
                </div>
                <!-- end widget div -->
        
              </div>
            </article>
            <!-- WIDGET END -->
        
          </div>
        
          <!-- end row -->
        
        </section>

      </div>  

app/views/events/new.html.erb
<%= render "layouts/left_panel" %>
<h1>Let's start with the basics...</h1>
<div id="event_error_explanation" style="display:none;">
</div>
<%= form_for(@event, :remote => true) do |f| %>
  <%= render 'new_event_details', :f => f %>
  <%= f.submit :class => "btn btn-primary" %>
<% end %>

app/views/events/show.html.erb
<% if @event.published %>
<body>
    <div id="main" role="main">
      <div class="wrapper">
        <h1 class="event-title"><span>EVENT : </span><%= @event.title %></h1><!-- /.event-title -->
        <div class="event-details">
          <ul class="reset">
            <li><i class="calendar"></i><%= @event.date %><span><%= @event.date.strftime('%A') %></span></li>
            <li><i class="clock"></i><%= @event.time.strftime('%l:%M') %><span><%= @event.time.strftime('%p') %></span></li>
            <li><i class="map-marker"></i><%= @event.street_address_one %><span><%= "#{@event.city}, #{@event.state} #{@event.zipcode}"%></span></li>
          </ul>
        </div><!-- /.event-details -->
        <!-- <div class="share-icon right">
          <ul class="reset">
            <li class="facebook"><a href="#">Facebook</a></li>
            <li class="twitter"><a href="#">Twitter</a></li>
            <li class="email"><a href="#">Email</a></li>
          </ul>
        </div><!-- /.share-icon -->
        <div class="clear"></div><!-- /.clear -->
        <div class="event-photo">
          <%= image_tag "psd_html/event-photo.png" %>
        </div><!-- /.event-photo -->
        <div class="event-tickets">
          <div class="labels">
            <div class="left">Ticket</div><!-- /.left -->
            <div class="left">Price</div><!-- /.right -->
          </div><!-- /.labels -->
          <div class="clear"></div><!-- /.clear -->
          <div class="tickets">
            <ul class="reset">
              <% @event.tickets.each do |ticket| %>
                <li>
                  <span class="name"><%= ticket.ticket_type %></span>
                  <span class="price"><%= number_to_currency(stripe_to_display(ticket.price)) %></span>
                  <%= link_to "Add to Cart", new_order_path(:event_id => @event, 'ticket' => ticket.ticket_type), :class => "btn-add" %>
                </li>
              <% end %>
            </ul>
          </div><!-- /.tickets -->
          <div class="icon-cc left">
            <ul class="reset">
              <li><a href="#" class="visa">VISA</a></li>
              <li><a href="#" class="amex">AMEX</a></li>
              <li><a href="#" class="maestro">Maestro</a></li>
              <li><a href="#" class="mastercard">Mastercard</a></li>
            </ul>
          </div><!-- /.icon-cc -->
        </div><!-- /.tickets -->
        <div class="clear"></div><!-- /.clear -->
        <div class="event-descriptions clearfix">
          <ul class="reset left tabs">
            <li class="active"><a href="#tab-1">Getting rad one city at a time<span>Color Me Why?</span></a></li>
            <li><a href="#tab-2">what's in it for me?<span>Packet Items, Race Day Activities</span></a></li>
            <li><a href="#tab-3">Packet Pickup Info<span>Outsmart the lines. Here's how</span></a></li>
            <li><a href="#tab-4">Race Day Info<span>What to expect on your big day</span></a></li>
            <li><a href="#tab-5">Deadlines and Pricing<span>Early bird gets it</span></a></li>
            <li><a href="#tab-6">Volunteer<span>Karma's a five letter word</span></a></li>
            <li><a href="#tab-7">Charity<span>Run FOR Something</span></a></li>
          </ul>
          <div class="tab-content left">
           <!--  <div class="share-icon right">
              <ul class="reset">
                <li class="facebook"><a href="#">Facebook</a></li>
                <li class="twitter"><a href="#">Twitter</a></li>
                <li class="email"><a href="#">Email</a></li>
              </ul>
            </div><!-- /.share-icon right -->
            <div id="tab-1" class="tab">
              <h1>Race Day Info</h1>
              <%= @event.about %>
            </div>
            <div id="tab-2" class="tab">
              <h1></h1>
              <%= @event.packet_info %>
            </div>
            <div id="tab-3" class="tab">
              <h1>Packet Pickup Info</h1>
              <%= @event.packet_pickup_info_html %>
            </div>
            <div id="tab-4" class="tab">
              <h1>Race Day Info</h1>
              <%= @event.race_day_info_html %>
            </div>
            <div id="tab-5" class="tab">
              <h1>Deadline and Pickup Info</h1>
              <%= @event.deadline_pricing_info %>
            </div>
            <div id="tab-6" class="tab">
              <h1>Volunteer</h1>
              <%= @event.volunteer_info %>
            </div>
            <div id="tab-7" class="tab">
              <h1>Charity Partner</h1>
              <%= @event.charity_info %>
            </div>

          </div><!-- /.tab-content -->
        </div><!-- /.tabs -->
        <!-- <div class="newsletter right">
          <label for="email">EVENT ANNOUNCMENT</label>
          <input type="text" id="email" name="email" placeholder="Email Address" />
          <button type="submit">SUBMIT</button>
        </div> --><!-- /.newsletter -->
      </div><!-- /.wrapper -->
    </div>
    <div class="clear"></div><!-- /.clear -->

    <%= render 'layouts/powered_by_footer.html' %>
    <%= render 'layouts/event/js_footer_event' %>
  </body>

<% else %>
    <h1>This event isn't live yet! Click <%= link_to "right here", publish_path(@event), :style => "color:blue;" %> to go to the publish tab.</h1>
<% end %>

app/views/events/waiver.html.erb
<%= @event.waiver %>