config/routes.rb
Downhill::Application.routes.draw do

  # require 'sidekiq/web'
  # mount Sidekiq::Web => '/sidekiq'

  match '/users/auth/email/callback' => 'omniauth_callbacks#authorize_campaign_monitor', via: [:get, :post]
  match '/users/auth/:action/callback' => 'omniauth_callbacks#authorize_stripe', via: [:get, :post]

  get '/validate_referral_code/:code/:event_id' => "orders#validate_referral_code", :path => "/validate_referral_code/:code/:event_id"
  get '/validate_email_uniqueness/' => "orders#validate_email_uniqueness", :path => "/validate_email_uniqueness/"

  post '/orders/:event_id' => "orders#create", :as => "/"

  devise_for :users
  devise_for :participants, :controllers => { :registrations => "participants" }


  resources :settings
  resources :users
  resources :participants
  resources :teams
  resources :customers
  resources :campaign_monitors


  get '/:event_id/fee' => "fee#index", :as => "fees"
  post '/fee/:event_id' => "fee#create", :as => "/"
  get '/fee/new' => "fee#new", :as => "new_fee"
  get '/edit/:id/fee' => "fee#edit", :as => "edit_fee"
  get '/fee/:id' => "fee#show", :as => "fee"
  put '/fee/:id' => "fee#update"
  patch '/fee/:id' => "fee#update"
  delete '/fee/:id' => "fee#destroy"

  get '/:event_id/ticket' => "ticket#index", :as => "tickets"
  post '/ticket/:event_id' => "ticket#create", :as => "/"
  get '/ticket/new' => "ticket#new", :as => "new_ticket"
  get '/edit/:id/ticket' => "ticket#edit", :as => "edit_ticket"
  get '/ticket/:id' => "ticket#show", :as => "ticket"
  put '/ticket/:id' => "ticket#update"
  patch '/ticket/:id' => "ticket#update"
  delete '/ticket/:id' => "ticket#destroy"

  get '/:event_id/waves' => "waves#index", :as => "waves"
  post '/waves/:event_id' => "waves#create", :as => "/"
  get '/waves/new' => "waves#new", :as => "new_wave"
  get '/edit/:id/waves' => "waves#edit", :as => "edit_wave"
  get '/waves/:id' => "waves#show", :as => "wave"
  put '/waves/:id' => "waves#update"
  patch '/waves/:id' => "waves#update"
  delete '/waves/:id' => "waves#destroy"

  get '/:event_id/promo_codes' => "promo_codes#index", :as => "promo_codes"
  post '/promo_codes/:event_id' => "promo_codes#create", :as => "/"
  get '/promo_codes/new' => "promo_codes#new", :as => "new_promo_code"
  get '/edit/:id/promo_codes' => "promo_codes#edit", :as => "edit_promo_code"
  get '/promo_codes/:id' => "promo_codes#show", :as => "promo_code"
  put '/promo_codes/:id' => "promo_codes#update"
  patch '/promo_codes/:id' => "promo_codes#update"
  delete '/promo_codes/:id' => "promo_codes#destroy"

  get '/:event_id/affiliate_settings' => "affiliate_settings#index", :as => "affiliate_settings"
  post '/affiliate_settings/:event_id' => "affiliate_settings#create", :as => "/"
  get '/affiliate_settings/new' => "affiliate_settings#new", :as => "new_affiliate_settings"
  get '/edit/:id/affiliate_settings' => "affiliate_settings#edit", :as => "edit_affiliate_settings"
  get '/affiliate_settings/:id' => "affiliate_settings#show", :as => "affiliate_setting"
  put '/affiliate_settings/:id' => "affiliate_settings#update"
  patch '/affiliate_settings/:id' => "affiliate_settings#update"
  delete '/affiliate_settings/:id' => "affiliate_settings#destroy"

  get '/:event_id/orders/new' => "orders#new", :as => "new_order"
  post '/orders/:event_id' => "orders#create", :as => "/"
  get '/:event_id/success' => "orders#success", :as => "success_order"

  get '/dashboard' => 'dashboards#show'

  get '/events/:id/registration' => "events#edit", :as => "registration"
  get '/events/:id/publish' => "events#edit", :as => "publish"
  get '/events/:id/other_info' => "events#edit", :as => "other_info"
  get '/events/:id/waiver' => "events#waiver", :as => "event_waiver"

  resources :events

  get '/events/:id/(/:referral_code)' => 'events#show', :as => "public_event"

  # get '/faq' => "pages#faq"
  root 'pages#home'

end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  validates :ticket_type, :presence => true
  validates :quantity, :presence => true, :numericality => { only_integer: true, :message => "needs to be an integer"  }
  validates :price, :numericality => {:greater_than => 0, :message => "needs to be bigger than 0"}

  belongs_to :event

  has_many :user_tickets
  has_many :users, :through => :user_tickets

  def free?
    self.price == 0
  end
  
end

app/controllers/ticket_controller.rb
class TicketController < ApplicationController
  before_action :authenticate_user!, :check_subdomain
  before_action :get_event_from_params, :only => [:create, :index]
  before_action :find_ticket, :only => [:edit, :update]

  def create
    @ticket = @event.tickets.build(ticket_params)
    
    respond_to do |format|
      if @ticket.save
        format.js { render :js => "window.location.href = '#{tickets_path}'" }
      else
        format.js
        # format.html { render 'new' }
      end
    end
  end

  def new
    @ticket = Ticket.new
  end

  def index
    @ticket = Ticket.new
    @tickets = @event.tickets
  end

  def edit
    @event = @ticket.event
  end

  def update
    if @ticket.update(ticket_params)
      redirect_to :back
    else
      redirect_to root_url
    end
  end

  private

  def find_ticket
    @ticket = Ticket.find_by id: params[:id]
  end

  def ticket_params
    params.require(:ticket).permit(
      :ticket_type,
      :price,
      :for_sale_begin,
      :for_sale_end,
      :quantity
      )
  end
  
end

app/helpers/ticket_helper.rb
module TicketHelper
end

app/views/ticket/_add_ticket_modal.html.erb
<div class="modal fade in" id="ticketModal" tabindex="-1" role="dialog" style="display: none;" aria-hidden="false">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
          ×
        </button>
        <h4 class="modal-title">
          Create Ticket
        </h4>
        <div id="ticket_error_explanation" style="display:none;">
        </div>
      </div>
      <div class="modal-body no-padding">

          <%= form_for @ticket, :url => { :action => :create }, :remote => true, html: {:class => "smart-form"} do |f| %>
              <fieldset>
          
                <section>
                  <div class="row">
                    <%= f.label :ticket_type, "Ticket name", :class => "label col col-2" %>
                    <div class="col col-10">
                      <label class="input"> <i class="icon-append fa fa-ticket"></i>
                        <%= f.text_field :ticket_type, :placeholder => "E.g. VIP" %>
                      </label>
                    </div>
                  </div>
                </section>

                <section>
                  <div class="row">
                    <%= f.label :price, :class => "label col col-2" %>
                    <div class="col col-10">
                      <label class="input"> <i class="icon-append fa fa-money"></i>
                        <%= f.text_field :price, :placeholder => "45.95" %>
                      </label>
                    </div>
                  </div>
                </section>

                <section>
                  <div class="row">
                    <%= f.label :quantity, :class => "label col col-2" %>
                    <div class="col col-10">
                      <label class="input"> <i class="icon-append fa fa-money"></i>
                        <%= f.text_field :quantity, :placeholder => "500" %>
                      </label>
                    </div>
                  </div>
                </section>

                <section>
                  <div class="row">
                    <%= f.label :for_sale_begin, "Start date", :class => "label col col-2" %>
                    <div class="col col-10">
                      <label class="input"> <i class="icon-append fa fa-calendar-o"></i>
                        <%= f.date_field :for_sale_begin, :format => "yyyy-MM-dd", :placeholder => "45.95" %>
                      </label>
                    </div>
                  </div>
                </section>

                 <section>
                  <div class="row">
                    <%= f.label :for_sale_end, "End date", :class => "label col col-2" %>
                    <div class="col col-10">
                      <label class="input"> <i class="icon-append fa fa-calendar-o"></i>
                        <%= f.date_field :for_sale_end, :format => "yyyy-MM-dd", :placeholder => "45.95" %>
                      </label>
                    </div>
                  </div>
                </section>


              </fieldset>
              
              <footer>
                <%= f.submit "Create Ticket", :class => "btn btn-primary" %>
              </footer>
              <% end %>
            </form>           
            

      </div>

    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div>

app/views/ticket/_form.html.erb
<%= render "layouts/event_header" %>

<%= form_for @ticket do |f| %>

  <div class="form-group">
    <%= f.label :ticket_type, "Ticket type" %>
    <%= f.text_field :ticket_type, :placeholder => "e.g. Volunteer", :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :price %>
    <%= f.text_area :price, :placeholder => "45.95", :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :for_sale_begin, "Ticket goes on sales on:" %>
    <%= f.text_area :for_sale_begin, :placeholder => "11/08/2014", :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :for_sale_end, "Ticket stops selling on:" %>
    <%= f.text_area :for_sale_end, :placeholder => "11/30/2014", :class => "form-control" %>
  </div>

  <%= f.submit "Save Changes", :class => "btn btn-primary" %>

<% end %>

app/views/ticket/create.js.erb
<% if @ticket.errors.count > 0 %>
    $('#ticket_error_explanation').html("");
  <% @ticket.errors.full_messages.each do |message| %>
    $('#ticket_error_explanation').append("<%= message %>");
    $('#ticket_error_explanation').append("<br>");    
  <% end %>
  document.getElementById("ticket_error_explanation").style.display = 'block';
<% else %>
  document.getElementById("ticket_error_explanation").style.display = 'none';
<% end %>

app/views/ticket/index.html.erb
<%= render "layouts/left_panel" %>
<%= render "add_ticket_modal" %>
<div id="main" role="main" style="margin-left: 200px;">
<div id="content">

<section id="widget-grid" class="">
        
          <!-- row -->
          <div class="row">
        
            <!-- NEW WIDGET START -->
            <article class="col-xs-12 col-sm-12 col-md-12 col-lg-12 sortable-grid ui-sortable">
        
            <div class="jarviswidget jarviswidget-sortable jarviswidget-color-blueLight" id="wid-id-0" data-widget-fullscreenbutton="false" data-widget-togglebutton="false" data-widget-deletebutton="false" data-widget-colorbutton="false"  data-widget-editbutton="false" role="widget" style="" data-widget-attstyle="jarviswidget-color-green">

              <header role="heading">
                  <span class="widget-icon"> <i class="fa fa-table"></i> </span>
              </header>
        
                <!-- widget div-->
                <div role="content">
  
                  <!-- widget content -->
                  <div class="widget-body no-padding">

                   <% if @tickets.blank? %>
                    <br>
                    <h1 style="font-size:30px; margin-left: 10px;">You haven't created any tickets yet.</h1>
                    <h4 style="font-size:15px; margin-left: 10px;">Make your first by clicking the "Add Ticket" button below!</h4>
                    <br>
                  <% else %>

                    
                    <!-- drop down filter -->

                      <!-- end search filter box -->

                     
                    <div class="dt-wrapper">
                      <table id="dt_basic" class="table table-striped table-bordered table-hover dataTable" aria-describedby="dt_basic_info">
                      <thead>
                        <tr role="row">
                          <th class="sorting" role="columnheader" tabindex="0" aria-controls="dt_basic" rowspan="1" colspan="1" aria-label="Name: activate to sort column ascending" style="width: 150px;">Ticket Name</th>
                          <th class="sorting" role="columnheader" tabindex="0" aria-controls="dt_basic" rowspan="1" colspan="1" aria-label="Phone: activate to sort column ascending" style="width: 126px;">Price</th>
                          <th class="sorting" role="columnheader" tabindex="0" aria-controls="dt_basic" rowspan="1" colspan="1" aria-label="Name: activate to sort column ascending" style="width: 150px;">Quantity</th>
                          <th class="sorting" role="columnheader" tabindex="0" aria-controls="dt_basic" rowspan="1" colspan="1" aria-label="Company: activate to sort column ascending" style="width: 110px;">Sale Begins</th>
                          <th class="sorting" role="columnheader" tabindex="0" aria-controls="dt_basic" rowspan="1" colspan="1" aria-label="Zip: activate to sort column ascending" style="width: 83px;">Sale Ends</th>
                        </tr>
                      </thead>
                      <tbody role="alert" aria-live="polite" aria-relevant="all">
                      <% @tickets.each do |ticket| %> 
                          <tr class="<%= cycle("odd", "even") -%>">
                            <td class=" "><%= link_to ticket.ticket_type, edit_ticket_path(ticket) %></td>
                            <td class=" "><%= number_to_currency(stripe_to_display(ticket.price)) %></td>
                            <td class=" ">
                              <% if ticket.users.count > 0 %>
                                <%= "#{ticket.quantity - ticket.users.count}/#{ticket.quantity}" %>
                              <% else %>
                                <%= "#{ticket.quantity}/#{ticket.quantity}" %>
                              <% end %>
                              </td>
                            <td class=" "><%= ticket.for_sale_begin %></td>
                            <td class=" "><%= ticket.for_sale_begin %></td>
                          </tr>
                      <% end %>
                      </tbody>
                    </table>

                  </div>
                
                <% end %>

                    </div>

                  </div>
                  <a data-toggle="modal" href="#ticketModal" class="btn btn-success btn-lg pull-left header-btn hidden-mobile"><i class="fa fa-circle-arrow-up fa-lg"></i>Add Ticket</a>
        
                  </div>
                  <!-- end widget content -->
        
                </div>
                <!-- end widget div -->
        
              </div>
            </article>
            <!-- WIDGET END -->
        
          </div>
        
          <!-- end row -->
        
        </section>
      </div>
      </div>